name: Python package

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8', 'pypy2', 'pypy3']
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      TOXENV: py
      HYPOTHESIS_PROFILE: ci
    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.python-version }} - ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Run tests
      run: |
        python -m tox
    - name: Report coverage
      run: |
        tox -e coverage-report,codecov

  other:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        toxenv: ["lint", "docs", "build"]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.toxenv }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install tox
        run: python -m pip install --upgrade pip tox
      - name: Run action
        run: |
          if [[ $TOXENV == "build" ]]; then
            TOXENV="build,build-check"
          fi

          if [[ $TOXENV == "docs" ]]; then
            tox -- -j auto -bhtml -W -n -a --keep-going
          else
            tox
          fi
